# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.protocode import audio_pb2 as audio__pb2


class GreeterStub(object):
    """Definicion del servicio Greeter
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RouteTranscribir = channel.unary_unary(
                '/transcribir.Greeter/RouteTranscribir',
                request_serializer=audio__pb2.TranscribirRequest.SerializeToString,
                response_deserializer=audio__pb2.TranscribirReply.FromString,
                )


class GreeterServicer(object):
    """Definicion del servicio Greeter
    """

    def RouteTranscribir(self, request, context):
        """Envio de solicitud
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RouteTranscribir': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteTranscribir,
                    request_deserializer=audio__pb2.TranscribirRequest.FromString,
                    response_serializer=audio__pb2.TranscribirReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transcribir.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Definicion del servicio Greeter
    """

    @staticmethod
    def RouteTranscribir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transcribir.Greeter/RouteTranscribir',
            audio__pb2.TranscribirRequest.SerializeToString,
            audio__pb2.TranscribirReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
